### PR TITLE
Add extension method toSingle

### PR DESCRIPTION
**Pull request by VovaStelmashchuk**
1. Add extension method `toSingle` for create a Single from object. Like an Observable from Collections.
2. Small code reformation.

### CODE REVIEW

**Comment by vpriscan** [comment]
Hi @jordan1997, you should pull upstream 2.x branch again to apply the fix for Travis build, there was a problem with JDK version (oraclejdk8 license was changed and it stopped working).

**Comment by VovaStelmashchuk** [comment]
@vpriscan Done.

**Comment by vpriscan** [comment]
@jordan1997 Thanks. The build is now passing. But I forgot to say, you should now target the new RxKotlin 3.x version. Version 2.x is now in maintenance mode, meaning no new features will be accepted.

**Comment by VovaStelmashchuk** [comment]
I cherry-pick my commit to 3.x, and create a new PR #231 , because i can change the source branch of exists PR.

**Pull request closed without merging**
