### PR TITLE
Add generic toSingle() extension function

### PR DESCRIPTION
**Pull request by svenjacobs**
Adds a generic `toSingle()` extension function which is just a delegate to `singleOf()`.

### CODE REVIEW

**Comment by orangy** [comment]
I strongly suggest against using extension functions on generic unbound types. They pollute code completion, slows down compiler. In this particular case it has also very generic name `toSingle()` which will be available on `Sequence<T>` for example, with a confusing meaning.

**Comment by svenjacobs** [comment]
@orangy Would be restricting `toSingle()` to primitive types be a better approach?

**Comment by orangy** [comment]
I don't see much value in using extension method here at all. `singleOf` is good enough.

**Comment by svenjacobs** [comment]
I thought since `singleOf(T)` already exists a delegating extension function on a generic type would not be such a problem since extension functions have to be explicitly imported.

**Comment by svenjacobs** [comment]
@MarioAriasC Any news on this?

**Comment by svenjacobs** [comment]
Closing this due to lack of feedback

**Pull request closed without merging**
