### PR TITLE
Make Subscribers immutable

### PR DESCRIPTION
**Pull request by MarcinMoskala**

### CODE REVIEW

**Comment by thomasnield** [comment]
This looks like it is based on very old code,  like from the 0.x branch.

**Comment by MarcinMoskala** [comment]
Still on branch 0.x

**Comment by thomasnield** [comment]
Okay,  this PR is not necessarily current then. The 1.x and 2.x branches reflect some major changes that occurred with this part of the API. 

You can feel free to look at those and propose any changes : )

**Comment by MarcinMoskala** [comment]
I already did. I am now writing tests.

**Pull request closed without merging**
