### PR TITLE
Add fromCallable function

### PR DESCRIPTION
**Pull request by lenguyenthanh**
This PR is for #71 and #70 with suggestion of @akarnokd

### CODE REVIEW

**Comment by JakeWharton** [comment]
You can already do `fromCallable { .. }` because of SAM conversion so why is this needed?

**Comment by lenguyenthanh** [comment]
Just to remove `Observable.`

**Comment by JakeWharton** [comment]
``` kotlin
import rx.Observable.fromCallable
```

gets you that

**Comment by lenguyenthanh** [comment]
Thanks man, I got this. Close again :D

**Pull request closed without merging**
