### PR TITLE
Migrate to Kotlin M13

### PR DESCRIPTION
**Pull request by cbruegg**
This PR migrates the source code to be compatible with Kotlin M13.

### CODE REVIEW

**Comment by cbruegg** [comment]
Now that's weird. My code changes shouldn't have caused any changes to the behaviour. Investigating..

Edit: I've taken a look at the failed test. I might be wrong, but shouldn't `generated.get()` return 100?
`generated` is initialized with the value 0. It is then incremented by one 100 times, so its final value should be 0 + 100 = 100.

**Comment by cy6erGn0m** [comment]
looks like `take` behaviour has changed. I guess it will fail without your changes too. We probably need to fix the test

**Comment by cbruegg** [comment]
Would it be ok to adapt the test within the scope of this PR? I could do it in that case.

**Comment by cy6erGn0m** [comment]
@cbruegg i believe you can do it

**Comment by cy6erGn0m** [comment]
Also I still see many warnings during compilation: it would be great to clean up all the occurrences

**Comment by cbruegg** [comment]
@cy6erGn0m I don't see any warnings with the 07c7c88 commit anymore.

**Comment by akarnokd** [comment]
Hello. I'm not into Kotlin and I assume you use RxJava's take() operator. The take() operator has been changed a few months ago to not request too much. Could you tell me what the tests supposed to verify?

**Comment by cy6erGn0m** [comment]
Failed test is

``` kotlin
    test fun `infinite iterable should not hang or produce too many elements`() {
        val generated = AtomicInteger()
        kotlin.sequence { generated.incrementAndGet() }.toObservable().
                take(100).
                toList().
                subscribe()

        assertEquals(101, generated.get())
    }
```

Looks like `take` used to take more elements than needed but now it is fixed

**Comment by akarnokd** [comment]
Thanks!

**Comment by MarioAriasC** [comment]
I'll merge it and deploy it at midnight UK time

**Pull request merged**
