### PR TITLE
implement Observable<Observable<T>> extension functions

### PR DESCRIPTION
**Pull request by thomasnield**
Implement mergeAll(), concatAll(), and switchLatest()

### CODE REVIEW

**Review by JakeWharton — APPROVED** [review]

**Comment by drothmaler** [comment]
I think `flatten`, `flattenAll` or simply `flatMap` would be a better name (instead of `mergeAll`).
Because `mergeAll` indicates (to me), that the [merge](http://reactivex.io/documentation/operators/merge.html) operator would be used (instead of [flatMap](http://reactivex.io/documentation/operators/flatmap.html))

**Comment by thomasnield** [comment]
But a merge() is essentially what a flatMap() does,   just dynamically for an unlimited number of sources via emissions. These conventions are already used in RxPy  as well.  But I'll be open to revision if that's what others want.

**Comment by drothmaler** [comment]
Sorry, my mistake... I thought, that `merge` would act similar to `zip` (where one observable 'waits' for the other). I should have looked at the linked documentation more seriously. :-S 

But than I still have another question: why didn't you just use [Observable.merge(Observable)](http://reactivex.io/RxJava/javadoc/rx/Observable.html#merge(rx.Observable)) instead of `flatMap`? This way you could avoid the extra mapping lambda. 
(Same for `switchLatest` -> [Observable.switchOnNext(Observable)](http://reactivex.io/RxJava/javadoc/rx/Observable.html#switchOnNext(rx.Observable)) and 
`concatAll` -> [Observable.concat(Observable)](http://reactivex.io/RxJava/javadoc/rx/Observable.html#concat(rx.Observable))

**Comment by thomasnield** [comment]
I'm afraid I don't follow. The Observables are being emitted already within the Observable. No lambda arguments are needed for these extension functions.

**Comment by drothmaler** [comment]
Well all three extension function that you added are using a mapping lambda (that is simply returning it's input)... e.g. 'concatMap _**{ it }**_'

**Pull request merged**
