### PR TITLE
Added Additional Singles Zip Helpers

### PR DESCRIPTION
**Pull request by matwood**
Added 3->9 sources to match what is available starting here:

https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/Single.java#L1113

### CODE REVIEW

**Comment by stepango** [comment]
Would be great to add some tests

**Comment by matwood** [comment]
These were just the additional definitions to help with the SAM typing issue in Kotlin. I didn't see any tests for the one that was already there, and I assumed because they are not very testable. If you have an idea how to test these, I can implement them.

**Comment by thomasnield** [comment]
If these are simply wrappers for the SAM issue, I don't think there's a huge need for unit tests. However, I will take a look at this and merge tomorrow. Thank you!

**Comment by stepango** [comment]
@matwood just checking params ordering should be enough, I know it's not super useful, but I'll prefer to have it

**Comment by matwood** [comment]
@stepango Parameter order tests added. I also cleaned up some formatting on the original commit.

**Review by stepango — APPROVED** [review]

**Comment by thomasnield** [comment]
I'll be in San Diego all this week so I won't be doing any GitHub work until I get back. @stepango you dont have to wait for me so you can merge whenever

**Pull request merged**
