### PR TITLE
RxKotlin 2.0 Release Candidate

### PR DESCRIPTION
**Pull request by thomasnield**
Hey @stepango,

I took your 2.x fork, made some changes to reflect what we did with 1.x, and pushed it as branch `2.x-dev` on the main repository. 

I swept to make sure that all `Flowable` and `Observable` variants were created, and remove any API that was removed in 1.x. 

I'll review again tomorrow to make sure nothing was missed, but this may be a good place to start considering a release candidate for 2.x. Let me know what you think.

### CODE REVIEW

**Comment by thomasnield** [comment]
I think we should move package convention from `rx.lang.kotlin` to `io.reactivex.rxkotlin` to match Maven coordinates. 

We can do that last after we review and merge.

**Comment by thomasnield** [comment]
I'll figure out why tests are failing as well...

**Comment by thomasnield** [comment]
Okay, fixed all test issues. Feel free to take a look at this branch. After that, I will move to the new package convention, archive the old 2.x under "2.x-old", and create a new "2x". The package rename will make the conflicts not worthwhile to address, and therefore no good reason to merge.

**Comment by stepango** [comment]
Thanks, @thomasnield looks good. I'll go through 1.0 and 2.0 RC once more to double check if anything is missed from the RC's.

Closed https://github.com/ReactiveX/RxKotlin/pull/94

**Pull request merged**
